# Generated by Django 3.2.7 on 2021-10-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
