# Generated by Django 3.2.7 on 2021-10-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211025_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
